app:
  name: example-api
  port: 9000
  version: 0.0.0

database:
  driver: pg
  connection:
    user: root
    password: password
    database: auth
    host: localhost
    port: 5432
  pool:
    min: 1
    max: 10

log:
  level: error

cors:
  origin: localhost

password:
  salt: picopico

jwks:
  uri: http://localhost:9000/.well-known/jwks.json
  cache: true

cookie:
  keys:
    - pico
  access:
    expiry: 3600
  refresh:
    expiry: 180
